
"""
Django settings for muebleria project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^!_a-^xirka#e9%3bk!46ni5&m*b75#wk=3+_ziomyf2eg#a_*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'muebles',
    'categorias',
    'easy_thumbnails',
    'sorl.thumbnail',
    'ckeditor',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'muebleria.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # SE LE DICE A DJANGO QUE BUSQUE LA CARPETA templates
        'DIRS': [os.path.join(os.path.dirname(__file__), 'templates'), ],
        # SE LE DICE A DJANGO QUE EN CADA APP BUSQUE LA CARPETA templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # LISTA DE MUEBLES RELACIONADOS COMO LINKS EN INFERIOR DE PAGINA
                'muebleria.context_processors.lista_link_muebles_relacionados',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'muebleria.wsgi.application'


# ---------------------- DATABASE ----------------------
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# user -> PVsXZdPM8bHdmDr
# db -> pkJ7QmbV6JyRAwh
# pwd -> mfq9CWcfMffkVQ3
#

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'pkj7qmbv6jyrawh',
        'USER': 'pvsxzdpm8bhdmdr',
        'PASSWORD': 'mfq9CWcfMffkVQ3',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
# ---------------------- DATABASE ----------------------

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# --------------------easy_thumbnails--------------------
# THUMBNAIL_ALIASES = {
#     '': {
#         'foto_1': {'size': (1200, 600), 'crop': 'smart', 'quality': 95},
#         'foto_2': {'size': (1200, 600), 'crop': 'smart', 'quality': 95},
#         'foto_3': {'size': (1200, 600), 'crop': 'smart', 'quality': 95},
#         'foto_4': {'size': (1200, 600), 'crop': 'smart', 'quality': 95},
#         'foto_5': {'size': (1200, 600), 'crop': 'smart', 'quality': 95},
# 'imagen_categoria': {'size': (600, 600), 'crop': 'scale', 'quality': 95},
#     },
# }
# THUMBNAIL_HIGH_RESOLUTION = True
# --------------------easy_thumbnails--------------------

# ----------------------STATIC & MEDIA FIELDS----------------------
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# PARA PONER CACHE LOS ARCHIVOS ESTATICOS EN PRODUCCION _DEBUG_=_False_
# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'
# PARA PONER CACHE LOS ARCHIVOS ESTATICOS EN PRODUCCION
STATIC_ROOT = os.sep.join(
    os.path.abspath(__file__).split(os.sep)[:-2] + ['static'])

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'muebleria/static'),
)

STATICFILES_FINDERS = (
    # BUSCA LOS ARCHIVOS ESTATICOS EN EL SISTEMA DE ARCHIVOS
    'django.contrib.staticfiles.finders.FileSystemFinder',
    # BUSCA LOS ARCHIVOS ESTATICOS EN LA CARPETAS DE LAS APLICACIONES
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)


MEDIA_ROOT = os.sep.join(
    os.path.abspath(__file__).split(os.sep)[:-2] + ['muebleria/media'])
# MEDIA_ROOT = os.path.join(BASE_DIR, 'muebleria/media')
MEDIA_URL = '/media/'

# ----------------------STATIC & MEDIA FIELDS----------------------
# ----------------------SEND EMAILS----------------------

EMAIL_USE_TLS = True
"""EMAIL_HOST = 'EMAIL_HOST'"""
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
"""EMAIL_HOST_USER = 'EMAIL_HOST_USER'"""
EMAIL_HOST_USER = 'nomackayu@gmail.com'
"""EMAIL_HOST_PASSWORD = 'EMAIL_HOST_PASSWORD'"""
EMAIL_HOST_PASSWORD = 'EMAIL_HOST_PASSWORD'

# ----------------------SEND EMAILS----------------------
# ---------------------------------- django-ckeditor ----------------------------------
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'UltraFull',
        'height': 300,
        'toolbar_UltraFull': [
            ['Source', '-', 'Save', 'NewPage', 'DocProps', 'Preview', 'Print', '-', 'Templates'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],
            ['Find', 'Replace', '-', 'SelectAll', '-', 'SpellChecker', 'Scayt'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField'],
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks', '-', 'About'],
        ],
        'forcePasteAsPlainText': True,
    },
}
# ---------------------------------- django-ckeditor ----------------------------------